/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appkonversiwaktu;

/**
 *
 * @author T480
 */
public class KonversiWaktu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiWaktu
     */
    public KonversiWaktu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        txtValfrom = new javax.swing.JTextField();
        lblF = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        txtValto = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbDetikF = new javax.swing.JRadioButton();
        rbMenitF = new javax.swing.JRadioButton();
        rbJamF = new javax.swing.JRadioButton();
        rbHariF = new javax.swing.JRadioButton();
        rbMingguF = new javax.swing.JRadioButton();
        rbBulanF = new javax.swing.JRadioButton();
        rbTahunF = new javax.swing.JRadioButton();
        rbDetikT = new javax.swing.JRadioButton();
        rbMenitT = new javax.swing.JRadioButton();
        rbJamT = new javax.swing.JRadioButton();
        rbHariT = new javax.swing.JRadioButton();
        rbMingguT = new javax.swing.JRadioButton();
        rbBulanT = new javax.swing.JRadioButton();
        rbTahunT = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI KONVERSI WAKTU");

        lblFrom.setText("Detik");

        txtValfrom.setText("1");

        lblF.setText("S");

        jLabel4.setText("From");

        lblT.setText("S");

        txtValto.setText("1");

        lblTo.setText("Detik");

        jLabel7.setText("To");

        jLabel8.setText("=");

        buttonGroup1.add(rbDetikF);
        rbDetikF.setSelected(true);
        rbDetikF.setText("Detik (S)");
        rbDetikF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDetikFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMenitF);
        rbMenitF.setText("Menit (Mn)");
        rbMenitF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenitFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbJamF);
        rbJamF.setText("Jam (H)");
        rbJamF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJamFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHariF);
        rbHariF.setText("Hari (D)");
        rbHariF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHariFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMingguF);
        rbMingguF.setText("Minggu (W)");
        rbMingguF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMingguFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBulanF);
        rbBulanF.setText("Bulan (M)");
        rbBulanF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBulanFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTahunF);
        rbTahunF.setText("Tahun (Y)");
        rbTahunF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTahunFActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbDetikT);
        rbDetikT.setSelected(true);
        rbDetikT.setText("Detik (S)");
        rbDetikT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDetikTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMenitT);
        rbMenitT.setText("Menit (Mn)");
        rbMenitT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenitTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbJamT);
        rbJamT.setText("Jam (H)");
        rbJamT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJamTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbHariT);
        rbHariT.setText("Hari (D)");
        rbHariT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHariTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMingguT);
        rbMingguT.setText("Minggu (W)");
        rbMingguT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMingguTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbBulanT);
        rbBulanT.setText("Bulan (M)");
        rbBulanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBulanTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbTahunT);
        rbTahunT.setText("Tahun (Y)");
        rbTahunT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTahunTActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrom)
                    .addComponent(jLabel4)
                    .addComponent(rbMenitF)
                    .addComponent(rbJamF)
                    .addComponent(rbHariF)
                    .addComponent(rbMingguF)
                    .addComponent(rbBulanF)
                    .addComponent(rbTahunF)
                    .addComponent(rbDetikF)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblF)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDetikT)
                    .addComponent(rbJamT)
                    .addComponent(rbHariT)
                    .addComponent(rbMingguT)
                    .addComponent(rbBulanT)
                    .addComponent(rbTahunT)
                    .addComponent(lblTo)
                    .addComponent(jLabel7)
                    .addComponent(rbMenitT)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblT)))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnHitung)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblF)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rbDetikF)
                        .addGap(18, 18, 18)
                        .addComponent(rbMenitF)
                        .addGap(18, 18, 18)
                        .addComponent(rbJamF)
                        .addGap(18, 18, 18)
                        .addComponent(rbHariF)
                        .addGap(18, 18, 18)
                        .addComponent(rbMingguF)
                        .addGap(18, 18, 18)
                        .addComponent(rbBulanF)
                        .addGap(18, 18, 18)
                        .addComponent(rbTahunF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rbDetikT)
                        .addGap(18, 18, 18)
                        .addComponent(rbMenitT)
                        .addGap(18, 18, 18)
                        .addComponent(rbJamT)
                        .addGap(18, 18, 18)
                        .addComponent(rbHariT)
                        .addGap(18, 18, 18)
                        .addComponent(rbMingguT)
                        .addGap(18, 18, 18)
                        .addComponent(rbBulanT)
                        .addGap(18, 18, 18)
                        .addComponent(rbTahunT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBulanFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBulanFActionPerformed
    lblFrom.setText("Bulan");
    lblF.setText("M");
    }//GEN-LAST:event_rbBulanFActionPerformed

    private void rbBulanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBulanTActionPerformed
    lblTo.setText("Bulan");
    lblT.setText("M");
    }//GEN-LAST:event_rbBulanTActionPerformed

    private void rbDetikFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDetikFActionPerformed
    lblFrom.setText("Detik");
    lblF.setText("S");
    }//GEN-LAST:event_rbDetikFActionPerformed

    private void rbMenitFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenitFActionPerformed
    lblFrom.setText("Menit");
    lblF.setText("Mn");
    }//GEN-LAST:event_rbMenitFActionPerformed

    private void rbJamFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJamFActionPerformed
    lblFrom.setText("Jam");
    lblF.setText("H");
    }//GEN-LAST:event_rbJamFActionPerformed

    private void rbHariFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHariFActionPerformed
    lblFrom.setText("Hari");
    lblF.setText("D");
    }//GEN-LAST:event_rbHariFActionPerformed

    private void rbMingguFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMingguFActionPerformed
    lblFrom.setText("Minggu");
    lblF.setText("W");
    }//GEN-LAST:event_rbMingguFActionPerformed

    private void rbTahunFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTahunFActionPerformed
    lblFrom.setText("Tahun");
    lblF.setText("Y");
    }//GEN-LAST:event_rbTahunFActionPerformed

    private void rbDetikTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDetikTActionPerformed
    lblTo.setText("Detik");
    lblT.setText("S");
    }//GEN-LAST:event_rbDetikTActionPerformed

    private void rbMenitTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenitTActionPerformed
    lblTo.setText("Menit");
    lblT.setText("Mn");
    }//GEN-LAST:event_rbMenitTActionPerformed

    private void rbJamTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJamTActionPerformed
    lblTo.setText("Jam");
    lblT.setText("H");
    }//GEN-LAST:event_rbJamTActionPerformed

    private void rbHariTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHariTActionPerformed
    lblTo.setText("Hari");
    lblT.setText("D");
    }//GEN-LAST:event_rbHariTActionPerformed

    private void rbMingguTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMingguTActionPerformed
    lblTo.setText("Minggu");
    lblT.setText("W");
    }//GEN-LAST:event_rbMingguTActionPerformed

    private void rbTahunTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTahunTActionPerformed
    lblTo.setText("Tahun");
    lblT.setText("Y");
    }//GEN-LAST:event_rbTahunTActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
        double waktuAwal = Double.parseDouble(txtValfrom.getText());
   
        // Deteksi satuan waktu asal
        String satuanAsal = "";
        if (rbDetikF.isSelected()) satuanAsal = "S";
        else if (rbMenitF.isSelected()) satuanAsal = "Mn";
        else if (rbJamF.isSelected()) satuanAsal = "H";
        else if (rbHariF.isSelected()) satuanAsal = "D";
        else if (rbMingguF.isSelected()) satuanAsal = "W";
        else if (rbBulanF.isSelected()) satuanAsal = "M";
        else if (rbTahunF.isSelected()) satuanAsal = "Y";

        // Deteksi satuan waktu tujuan
        String satuanTujuan = "";
       if (rbDetikT.isSelected()) satuanTujuan = "S";
        else if (rbMenitT.isSelected()) satuanTujuan = "Mn";
        else if (rbJamT.isSelected()) satuanTujuan = "H";
        else if (rbHariT.isSelected()) satuanTujuan = "D";
        else if (rbMingguT.isSelected()) satuanTujuan = "W";
        else if (rbBulanT.isSelected()) satuanTujuan = "M";
        else if (rbTahunT.isSelected()) satuanTujuan = "Y";
       
       // konversi waktu asal ke detik dulu
        double detik = 0;
        detik = switch (satuanAsal) {
            case "S" -> waktuAwal;
            case "Mn" -> waktuAwal * 60;
            case "H" -> waktuAwal * 3600;
            case "D" -> waktuAwal * 86400;
            case "W" -> waktuAwal * 604800;
            case "M" -> waktuAwal * 2592000; // 30 hari
            case "Y" -> waktuAwal * 31536000; // 365 hari
            default -> waktuAwal;
        };
        
        // konversi dari detik ke satuan tujuan
        double hasil = 0;
        hasil = switch (satuanTujuan) {
            case "S" -> detik;
            case "Mn" -> detik / 60;
            case "H" -> detik / 3600;
            case "D" -> detik / 86400;
            case "W" -> detik / 604800;
            case "M" -> detik / 2592000; // 30 hari
            case "Y" -> detik / 31536000; // 365 hari
            default -> waktuAwal;
        };
    
      txtValto.setText(String.format("%.2f", hasil));
    } catch(NumberFormatException e) {
        txtValto.setText("Masukkan angka valid!");
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiWaktu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton rbBulanF;
    private javax.swing.JRadioButton rbBulanT;
    private javax.swing.JRadioButton rbDetikF;
    private javax.swing.JRadioButton rbDetikT;
    private javax.swing.JRadioButton rbHariF;
    private javax.swing.JRadioButton rbHariT;
    private javax.swing.JRadioButton rbJamF;
    private javax.swing.JRadioButton rbJamT;
    private javax.swing.JRadioButton rbMenitF;
    private javax.swing.JRadioButton rbMenitT;
    private javax.swing.JRadioButton rbMingguF;
    private javax.swing.JRadioButton rbMingguT;
    private javax.swing.JRadioButton rbTahunF;
    private javax.swing.JRadioButton rbTahunT;
    private javax.swing.JTextField txtValfrom;
    private javax.swing.JTextField txtValto;
    // End of variables declaration//GEN-END:variables
}
